### ISSUE TITLE
Nuget strategy for 64bit

### ISSUE THREAD

**Issue by msevestre** [msevestre/OSPSuite-64bit#6]
Is there anything we have to change to make nuget package work with our 64bit packages / app?

Suggestion would be to 

- create a 64bit app 
- reference SimModel package 3.0.0.8+ 
- see if there are any issue with the way we package our component. Hopefully this will work out of the box like for 32bit but we may have to do something special

**Comment by rwmcintosh** [comment]
I guess we can close these issues relating to 64 bit suite now!
